### ISSUE TITLE
Bug: jsDelivr isValidPackageName check is wrong

### ISSUE THREAD

**Issue by Feavy** [volarjs/volar.js#101]
Hello,

Function `isValidPackageName` rejects packages whose name contain a dot while some valid packages contain dots.  
Example : pixi.js https://www.jsdelivr.com/package/npm/pixi.js

https://github.com/volarjs/volar.js/blob/007ed5afed0f9447f9c932e63c54e02168f8155f/packages/cdn/lib/cdns/jsdelivr.ts#L206

I don't know exactly the goal of this check, but if it aims to rejects local modules (`import x from "./X"`) then this would be better:
```ts
if (pkgName.indexOf('.') == 0 || pkgName.endsWith('/node_modules')) { 
```

Thank you,

**Comment by johnsoncodehk** [comment]
I don't remember the exact purpose of this condition, I will remove this condition and see if it causes any regressions.
