### ISSUE TITLE
[v2] request handlers and context access in `ServerPlugin`

### ISSUE THREAD

**Issue by Andarist** [volarjs/volar.js#110]
I enjoy using Volar - great work!

I found myself in need to:
- implement custom requests to handle the extension commands and more
- get access to the TS program to analyze the AST

With the help of @remcohaszing I managed to do both of those based on:
- how the Vue's extension is using `onRequest`, [here](https://github.com/vuejs/language-tools/blob/e7439aa2dad3d6735bb75b1b099bfa26b05c7576/packages/language-server/src/languageServerPlugin.ts#L80)
- how the `volar-service-typescript-twoslash-queries` is getting access to the TS language service, [here](https://github.com/volarjs/services/blob/cc7ab7cae02da6b1f9c2d3bef468c404b67728f5/packages/typescript-twoslash-queries/src/index.ts#L12)

With those references and some source code spelunking I managed to do something along those lines:
```ts
export const createServerPlugin =
  (connection: Connection): ServerPlugin =>
  ({ modules }) => {
    return {
      typescript: {
        extraFileExtensions: [],
      },

      watchFileExtensions: [
        'cjs',
        'cts',
        'js',
        'jsx',
        'json',
        'mjs',
        'mts',
        'ts',
        'tsx',
      ],

      async resolveConfig(config, env, projectContext) {
        if (!modules.typescript) {
          throw new Error('TypeScript module is missing');
        }

        (config.services ||= {}).typescript = createTypeScriptService(
          modules.typescript,
        );

        return config;
      },
      onInitialized(projects) {
        connection.onRequest(helloRequest, async ({ textDocument, name }) => {
          if (!textDocument) {
            connection.console.log(`Hello, ${name}!`);
            return true;
          }
          const languageService = await getTypeScriptLanguageService(
            textDocument.uri,
          );

          connection.console.log(
            `Hello in "${languageService
              .getProgram()
              ?.getCurrentDirectory()}", ${name}!`,
          );
          return true;
        });

        async function getTypeScriptLanguageService(uri: string) {
          return (await projects.getProject(uri))
            .getLanguageService()
            .context.inject<Provide, 'typescript/languageService'>(
              'typescript/languageService',
            );
        }
      },
    };
  };
```

I think there is some opportunity in the API to make this use case easier

**Comment by johnsoncodehk** [comment]
Hi, thank you for your advice! I'm working on #113 related API refactoring, if you have any opinions please let me know. :)

**Comment by Andarist** [comment]
I think I like how `connection` can now be used in a more natural way (so it's "easier" - even if not really - to use `onRequest` and more).

That being said:
1. I think that Volar could have its way of using APIs like `onRequest`/`sendRequest`/more. The ones provided by `vscode-languageserver` are kinda full of typing footguns.
2. Implementation of `getTypeScriptLanguageService` here is still "complicated". I'm still learning this whole architecture and I understand that a server doesn't quite run within a context of a particular project so maybe it's just how it has to look like. It took me a while to figure this one out at first - but if you document this then I think it might be fine. Personally, I don't have a problem with copy-pastable snippets - it's not like everything has to have a lot of sugar on top of it.
3. I was also quite confused about the `env` parameter in `resolveConfig`. I found a similar `env` (although probably not the same) in different places in the API and in `resolveConfig` it was even optional. I see that `resolveConfig` is gone now so this has likely already been improved 👍 For context: I'm using `env.uriToFileName`

**Comment by johnsoncodehk** [comment]
You need to use some trick to manage request types. Not sure if it will help you, but you can refer to: https://github.com/vuejs/language-tools/blob/master/packages/language-server/src/protocol.ts

Here are the `RuntimeEnvironment` of the language server and the `ServiceEnvironment` of the language service.

- `RuntimeEnvironment`: Defines behavior specific to node or browser
- `ServiceEnvironment`: Defines the execution context of a LanguageService instance, which includes some methods from `RuntimeEnvironment`

**Comment by Andarist** [comment]
> You need to use some trick to manage request types.

I already have this part figured out. It's just that regardless of how those types are organized you still end up passing them to the "raw" `onRequest` API and that has suboptimal types (and thus suboptimal DX). Just take a look at this [TS playground](https://www.typescriptlang.org/play?ts=5.3.2#code/JYWwDg9gTgLgBAKjgQwM5wG6oMYQCYCmcAZlBCHAERa6EC0ANsgHYDmArsqwagVBnzpgyMCLgaUA3HAD0MuDACeYHgC44AZgB0ARgDsWgKwAoUJFhwA3nGxQCyGAQDCEZswLYYwV3AC+JMgpKAAEMCCYoGSY2Tm46Xn4+GWZ8Ai0AK1QpWXklFVR1ACYtAAZSumQGMAALZF0S42NmZBAeMGRsIgAJAgYGCAAlAgBHdh54S2M4OAIAD3N4PKIABWQoFtQAFWUiAF4rKemFOZgAETF2VuYYAH51GlStTZPz7EuCa4BJQmvgYmA+HAAD5wdjMQj-dx4SSHabNVrqVAwKDANgw6a+dEzebQRY7OBDVCQZi8bYqOD7ABGEHC9mYWLmCwU+IAolAyFAyXs4O4BFAGTiLLgSXjyft3AB3TA4R5DUbjLkAHlhcFW6xAWx2ABoVYTiaTtSq2RyuYcAHwACkojiRMmqvX6lAAlDDfI1hUibK53J5vMwKTY7A5nN6PF5XBaXY05DyIPBkHB7VViOwGDN2dBEA4UH0EMZhT7w8wtK45WMkRaen1BiNyzAtEstXBIxSzVZfFH86Hfa4S8wy+NKw6a-KkQ3tc3rI5ZmcLld4B3Wwdpn9mwBCaezt7zp3Lo4xiXIYDxuC8YV4NdwECKOAAAyr-QHSNvp5U2D+ALwd+ptJYL7Qd56q4BoqP+4JwIoBCLNUwDoB074-DAlQMDe8EEGAjhfiwoLggQkIEF+dgwOwUD+vadgqkRJH0nAhxuocVGkQoUBjK6UZAA)

I also prepared a standalone version that demonstrates the second problem: [TS playground](https://www.typescriptlang.org/play?ts=5.3.2#code/CYUwxgNghgTiAEkoGdnwEogI4FcTIBcAVATwAcQAeABQBoN6BRAPngG8AoeeOKYAewB2EEvAD6ALngBtOg3iMAuvAA+8HINAAzAJaCQwANwcAvhw4FyCABJRNEEDEzIcEApXRNWAXgzGOegSOWlBgCJi4+AS29o409J4KrJzcABRksFAAtshS1ACUUjHADk74ru6JLMZmHAD0dfAABgBy-ACSglqOTerIBvB6zQAWdiU98LoAHvjwBMM6yBZW8G2d3TCURD4yRIrSRPAgU0GaaHaiAPzwAAzwUvoAbo6K-qBIcJMaYAQ6QvBCCJ4QjxeQsVJcOZWKRAqKkCigqrMWiQ0axGAw7DA6JjUqIrwowrwR78HRGczvaCfMBCQg8bCYyKEeFUSEpbhzY4EAAi-DAOCyIEEBEuUkIMD0AHNVOpNCBdPpyRz4IJsiAxQQJYJJcZuCYUdwAEb8fgOOwGlUgZ4wDjMfyArFRVJwLD0VJsTknXn8wXC+AmfLwbzJSE6LTwVIAQiCXr5AqFBED7O4cAIOBggkM8AaAP4ZDQEkekLMKZAaYzcxgeBq+WMQA)

I know that `vscode-languageserver-protocol` is an official~ package and it might take a lot of time to improve this situation there because they have to be concerned about backward compatibility and stuff. Volar doesn't exactly have the same problems and I think that it could improve the situation quite dramatically here by providing its own set of types for those scenarios. I could help to brainstorm/write types for this.

**Comment by johnsoncodehk** [comment]
I understand your problem now, you need to always use "satisfies" to solve the DX problem:

```ts
connection.onRequest(HelloRequest.type, () => {
  return {

	// error message helpful now
  } satisfies HelloRequest.ResponseType;
});
```

**Comment by Andarist** [comment]
I knew how to deal with this **once** I recognized the problem. I think my overall issue stands though - the fact that I had to notice the problem is the DX problem. New users won't always notice that and I'm also quite proficient when it comes to dealing with TS issues so it was no problem at all to me in that sense. 

The `satisfies` solution is nice-ish but it requires some extra steps - it doesn't really solve the first issue (unhelpful error message) because when I just start typing out the `onRequest` call I don't even have my return statement written yet and the error is already reported. People will learn how to deal with this after adding a request or two to the codebase but a new contributor won't have that knowledge.

If we already encapsulate types using `vscode.RequestType` I don't see an extra annotation (either through `satisfies` or through an explicit return type annotation) as a perfect solution. TypeScript already has the information that it needs to typecheck this (it's encapsulated in the first argument) - it just fails to limit its inference to that argument alone (and to the "proper" overload). Extra annotations are sometimes required but when they are not... it's kinda nice to omit them since they are noisy and require more code to be written (and all of the relevant pieces to be updated when we make changes).

It's not a big issue for me at all. I will probably just end up wrapping things in a layer that provides better types but I wish that I wouldn't have to do that and that future Volar users wouldn't have to deal with those kinds of problems altogether :)

**Comment by johnsoncodehk** [comment]
Thank you for sharing your insights! In order to support the new RequestType, in addition to `vscode-languageserver`, we also need to add onRequest and sendRequest for BaseLanguageClient from `vscode-languageclient`. (Furthermore, there are also onNotification and sendNotification for server + client.) I'm not sure if this will introduce too much context. And I'm not sure if it's appropriate to trade increased context for DX improvements.

Can you try this approach in your project first? That way, we can review it in practice. Or once you think this is the appropriate method, please open a PR!
