### ISSUE TITLE
Allow the TypeScript plugin to be configured via editor settings

### ISSUE THREAD

**Issue by remcohaszing** [volarjs/volar.js#114]
Based on the VSCode documentation on [`contributes.typescriptServerPlugins`](https://code.visualstudio.com/api/references/contribution-points#contributes.typescriptServerPlugins), it’s possible to send configuration via an extension.

We could use this to provide a uniform interface to configure Volar based TypeScript plugins through either `tsconfig.json` or VSCode settings.

The following VSCode extension:

```ts
import { activateTsPlugin } from '@volar/vscode'

export async function activate(context) {
  await activateTsPlugin(
    '@mdx-js/typescript-plugin',
    context,
    'mdx',
    'config'
  )
}
```

configures the TypeScript plugin using the following VSCode settings:

```jsonc
{
  "mdx.config": {
    "plugins": []
  }
}
```

The TypeScript plugin would look something like this:

```ts
module.exports = createAsyncTSServerPlugin(
  ['.mdx'],
  2,
  // This tells Volar at which `tsconfig.json` key to look.
  'mdx',
  async (ts, info, options) => {
    // The options are available here somehow.
  }
)
```

This would be equivalen to having the following `tsconfig.json`:

```jsonc
{
  "compilerOptions": {/* … */},
  "mdx": {}
}
```

Related:
- https://github.com/mdx-js/mdx-analyzer/issues/354
- https://github.com/mdx-js/mdx-analyzer/issues/352#issuecomment-1809657265

**Comment by johnsoncodehk** [comment]
Closed due to no longer have needs on this. (Refs: https://github.com/mdx-js/mdx-analyzer/issues/354#issuecomment-2090621970)
