### ISSUE TITLE
Add virtual file tester

### ISSUE THREAD

**Issue by remcohaszing** [volarjs/volar.js#115]
The main purpose of a language plugin, is to provide (embdded) virtual files. These virtual files contain a snapshot and mappings. The [Volar Labs](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volarjs-labs) VSCode extension provides a great way to inspect them. However, the mappings become pretty hard to interpret when writing tests ([example](https://github.com/mdx-js/mdx-analyzer/blob/main/packages/language-service/test/language-module.js#L690-L704)).

It would be nice if Volar provides a way to represent virtual files in a way that’s friendly to the reader.

Idea: Add a function to represent a Volar virtual file as a markdown file containing annotated code blocks.

```js
import { printVirtualFile } from '@volar/test-utils'

printSnapshot(printVirtualFile, {
  comments: {
    markdown: ['<!--', '-->'],
    mdx: ['{/*', '*/}'],
    typescriptreact: '//',
  }
})
```

````md
```mdx fileName="file.mdx"
{/* Exact match */}
    import { Component } from './component.js'

    Hello <Component name={props.name} />
```

```javascriptreact fileName="file.mdx.jsx"
   import { Component } from './component.js'
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   /**
    * @deprecated
    *   Do not use.
    *
    * @param {{readonly [K in keyof MDXContentProps]: MDXContentProps[K]}} props
    *   The [props](https://mdxjs.com/docs/using-mdx/#props) that have been passed to the MDX component.
    */
   function _createMdxContent(props) {
     return <><Component name={props.name} /></>
//            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   }
   
   /**
    * Render the MDX contents.
    *
    * @param {{readonly [K in keyof MDXContentProps]: MDXContentProps[K]}} props
    *   The [props](https://mdxjs.com/docs/using-mdx/#props) that have been passed to the MDX component.
    */
   export default function MDXContent(props) {
     return <_createMdxContent {...props} />
   }
   
   // @ts-ignore
   /** @typedef {0 extends 1 & Props ? {} : Props} MDXContentProps */
```

```markdown fileName="file.mdx.md"

<!-- ^ --->
     Hello <!---->
<!-- ^^^^^^       ^ -->
```
````

The comment could be configured per language ID. Code is indented by the length of the opening comment. The commend uses `^` to indicate a character that matches the position in the parent virtual file, and shows the original character in case of a mismatch.

This file could be written to disk using any snapshotting library, or inlined in a multiline string.

**Comment by johnsoncodehk** [comment]
Good idea! 👍 Will look into this.

**Comment by remcohaszing** [comment]
Maybe the markdown formatting is a bit much. The result can be `Map<VirtualFile, string>`, where each virtual file is mapped to its representation.
