### ISSUE TITLE
Integrate for coc language client

### ISSUE THREAD

**Issue by johnsoncodehk** [volarjs/volar.js#12]
The coc API is very similar to vscode, I think it is suitable to integrate it in the core.

**Comment by haikyuu** [comment]
I use emacs as my daily editor, and I was wondering if it already works out of the box or is some work needed? How is volar linked to VSCode?

**Comment by johnsoncodehk** [comment]
I am aware that some people use volar with emacs, but since I do not use emacs, I cannot answer how. I suggest you inquire with the emacs community.

**Comment by johnsoncodehk** [comment]
Closed because I haven't found this a real need yet, and from a maintenance point of view we should avoid maintaining packages in this repo that won't be tested during the development phase.
