### ISSUE TITLE
Manually add dts files

### ISSUE THREAD

**Issue by kylehue** [volarjs/volar.js#22]
Is there a way for me to manually add dts files instead of having them auto-fetched?

**Comment by johnsoncodehk** [comment]
Please ref to https://github.com/vuejs/repl/blob/main/src/monaco/vue.worker.ts, you can provide your own file system provide.

```ts
const env = createServiceEnvironment();
env.fs = {
  readDirectory() {
    // ...
  },
  readFile() {
    // ...
  },
  stat() {
    // ...
  },
}
```
