### ISSUE TITLE
"Save as..." in VSCode often triggers "Virtual script not found" error

### ISSUE THREAD

**Issue by matthew-dean** [volarjs/volar.js#23]
Obviously there's no way to repro this in a repo, because this is an extension bug in VSCode, but on more than one occasion, if I'm working with a Vue SFC (in TypeScript), and I "Save as..." another file in the same folder, the script tag will say: `Virtual script not found, may missing <script lang="ts"> / "allowJs": true / jsconfig.json`

`allowJs` is enabled and was working just fine in tsconfig.json. Creating a `jsconfig.json` of course has no effect, because it's TypeScript (but I tried anyway). It happens only when duplicating a file. Restarting Volar is the only current fix.

**Comment by johnsoncodehk** [comment]
I think this problem no longer exists. If not, please open an issue in the vuejs/language-tools repo.
