### ISSUE TITLE
Can source-map README be written in more detail?

### ISSUE THREAD

**Issue by chapaofan-zy** [volarjs/volar.js#237]
Can source-map README be written in more detail?

or

How to transform a source-map like ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;CAAA;AACA,SAAS,EAAE,KAAK,CAAE,CAAC,CAAE,MAAM,EAAE,CAAE;AAC/B,sBAAsB,EAAE,CAAE;AAC1B,UAAU,EAAE,CAAE;AACd,SAAS,EAAE,CAAE;AACb;AACA" to 

```ts
export interface Mapping<Data = unknown> {
    sourceOffsets: number[];
    generatedOffsets: number[];
    lengths: number[];
    generatedLengths?: number[];
    data: Data;
}
```

**Comment by johnsoncodehk** [comment]
You need to use `@jridgewell/sourcemap-codec` to decode this string and then convert it. There is a complete demonstration code from withastro/language-tools: https://github.com/withastro/language-tools/blob/af5bbc5f6b4f0a66113d7050a85824078ffaaeac/packages/ts-plugin/src/astro2tsx.ts#L60-L124

**Comment by chapaofan-zy** [comment]
thx, just don't know `number[]` means in 
```ts
export interface Mapping<Data = unknown> {
    sourceOffsets: number[];
    generatedOffsets: number[];
    lengths: number[];
    generatedLengths?: number[];
    data: Data;
}
```
