### ISSUE TITLE
runTsc breaks in Typescript v5.7 when providing `extraSupportedExtensions`

### ISSUE THREAD

**Issue by kitsune7** [volarjs/volar.js#251]
When using the [runTsc function](https://github.com/volarjs/volar.js/blob/3e996b3a4c435ccd52b1ce681f603af08df123d4/packages/typescript/lib/quickstart/runTsc.ts#L10) from the `@volar/typescript` npm package, the code will break if the user has Typescript v5.7 or higher and they have a non-empty array provided on the `extraSupportedExtensions` option (see [this issue](https://github.com/vuejs/language-tools/issues/5018) for an example).

This happens because in Typescript v5.7, [they start making use of a shim](https://github.com/microsoft/TypeScript/pull/59720) in order enable Node.js/v8 compile caching. This means that the `tscPath` provided to `runTsc` may be a shim that pulls in the main code. It's no longer safe to assume like we do in [transformTscContent](https://github.com/volarjs/volar.js/blob/3e996b3a4c435ccd52b1ce681f603af08df123d4/packages/typescript/lib/quickstart/runTsc.ts#L61) that the `tsc` argument includes any of the code we want to update.

I spent quite a while digging through to code to figure out the exact issue. I'm happy to submit a PR to fix the issue, but I thought it might be best to submit an issue first in case we wanted to discuss what the ideal solution would look before I start messing with code.

The easiest way I can see to solve it off the top of my head would be to add a check for the file that gets `require`d at the end of the file at the `tscPath` if it's missing the content that we expect, but that could be finicky. I'm open to suggestions.

**Comment by kitsune7** [comment]
Since Volar relies on parsing Typescript's source code, it's not immune to updates, but I put up a [PR](https://github.com/volarjs/volar.js/pull/252) that makes the safest assumptions about the structure of the code that I can think to make. I'm happy to change things if someone has a better idea on how to handle it, but the changes _do_ fix the problem while maintaining backwards compatibility.

**Comment by silverwind** [comment]
> parsing Typescript's source code

This seems insane. Why not contribute the necessary APIs that you need to Typescript and have volar function as a plugin to typescript, enabling users to run the official `tsc`? Would be much cleaner and not break every new Typescript release.
