### ISSUE TITLE
Type definitions are not loaded immediately after tsserver startup when using `createAsyncLanguageServicePlugin`

### ISSUE THREAD

**Issue by mizdra** [volarjs/volar.js#254]
## Summary

The behavior immediately after `tsserver` initialization is different between `createAsyncLanguageServicePlugin` and `createLanguageServicePlugin`.

In `createLanguageServicePlugin`, `tsserver` loads the type definitions of the files that Volar.js processes. However, `createAsyncLanguageServicePlugin` does not.

## How to repdoduce

reproduction: https://github.com/mizdra/playground-volar-typescript-service-plugin/pull/1/commits/e73b0e13b73c1b6e6ae42b2e37894941a71bdd75

1. Checkout https://github.com/mizdra/playground-volar-typescript-service-plugin/pull/1/commits/e73b0e13b73c1b6e6ae42b2e37894941a71bdd75
1. Open workspace on VS Code
1. When the tsdk switching prompt appears, select "Allow".
1. Open `example/index.ts` in the tab
1. Restart tsserver

https://github.com/user-attachments/assets/dac3a932-8fd0-480b-8a29-433ba79a15ec

## Expected behavior

`tsserver` loads the type definitions of `ts-logo-256.png`.

## Actual behavior

`tsserver` does not load the type definitions of `ts-logo-256.png`. When import specifier is changed, the tsserver loads the type definition.

**Comment by mizdra** [comment]
Is this a bug? Or is this expected behavior? Are there any technical limitations with `createAsyncLanguageServicePlugin`?

**Comment by johnsoncodehk** [comment]
A quick look, `createAsyncLanguageServicePlugin` relies on using `markAsDirty` to refresh diagnostics after initialization, the problem may be that `markAsDirty` is no longer working now. (I haven't tried the repro case yet.)

https://github.com/volarjs/volar.js/blob/3e996b3a4c435ccd52b1ce681f603af08df123d4/packages/typescript/lib/quickstart/createAsyncLanguageServicePlugin.ts#L107

**Comment by mizdra** [comment]
I confirmed that the problem has been fixed. Thank you!
