### ISSUE TITLE
volar fails to start due to a syntax error

### ISSUE THREAD

**Issue by vincent-olivert-riera** [volarjs/volar.js#29]
Hello,

Using NeoVim I have installed the `volar` LSP via `Mason`.
Now, when I edit a `.vue` file, the volar LSP client immediately crashes with exit code 1 and signal 0.

This is the complete output in `lsp.log` (I will split it in multiple lines for readability):

```
[START][2023-04-16 09:06:32] LSP logging initiated
[ERROR][2023-04-16 09:06:32] .../vim/lsp/rpc.lua:734	"rpc"	"vue-language-server"	"stderr"
"/home/vincent/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/
  vue-language-server/node_modules/@vscode/l10n/dist/main.js:846
throw new Error(e.responseText ?? (0, import_request_light.getErrorStatusDescription)(e.status) ?? e.toString());

SyntaxError: Unexpected token '?'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at /home/vincent/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/
  vue-language-server/node_modules/vscode-html-languageservice/lib/umd/parser/htmlScanner.js:17:18
at /home/vincent/.local/share/nvim/mason/packages/vue-language-server/node_modules/@volar/
  vue-language-server/node_modules/vscode-html-languageservice/lib/umd/parser/htmlScanner.js:7:17
at Object.<anonymous> (/home/vincent/.local/share/nvim/mason/packages/vue-language-server/
  node_modules/@volar/vue-language-server/node_modules/vscode-html-languageservice/lib/umd/parser/
  htmlScanner.js:13:3)"
```

**Comment by johnsoncodehk** [comment]
Maybe your Node version too old,Node <= 14 do not support double question mark operator.

**Comment by vincent-olivert-riera** [comment]
Uhm..., it could be. It's the one in Debian stable. I'll check when I get back home.

**Comment by vincent-olivert-riera** [comment]
> Maybe your Node version too old,Node <= 14 do not support double question mark operator.

https://packages.debian.org/search?suite=bullseye&keywords=nodejs

Yeah, it must be that. The current version of `nodejs` in Debian stable is 12.22.5.

It's unfortunate that this project is not compatible with such an important distro like Debian :-( I wonder if it was really necessary to use modern syntax like that.

**Comment by johnsoncodehk** [comment]
`@vscode/l10n` is an external dependency we can't control. But Node 12 is too old anyway, you should ask Debian to update it.

**Comment by vincent-olivert-riera** [comment]
> `@vscode/l10n` is an external dependency we can't control.

Fair enough 👍

> But Node 12 is too old anyway, you should ask Debian to update it.

Hehe, yeah... It won't happen. I will need to install nodejs from another source.

Thanks for you answer. I will close this issue now.

**Comment by ynsssss** [comment]
I use node v21.5.0 but problem persists. Error is exactly the same
