### ISSUE TITLE
Add source.sortImports support for .vue files in Volar

### ISSUE THREAD

**Issue by dshinton-qstart** [volarjs/volar.js#34]
# Preamble

I think this issue needs to be in [language-tools](https://github.com/vuejs/language-tools), but that repo has limited issue reporting to existing contributors, so I can't post this there. If it does need to be moved, I would appreciate a contributor adding it over there. Thank you in advance!

# Request

I use VS Code for Vue development with the Volar plugins. In my VS Code config I used to use `source.organizeImports` in `editor.codeActionsOnSave` but it deletes unused imports which can break an application. I read that [VS Code v1.57](https://code.visualstudio.com/updates/v1_57#_sort-imports-source-action) added the `source.sortImports` action for javascript and typescript files. However, this action has no effect on .vue files.

Please add `source.sortImports` support for .vue files so I can automatically organize my inputs in a non-destructive manner.

Thank you!

**Comment by johnsoncodehk** [comment]
Coincidentally this is not a vuejs/language-tools issue, I'll be tracking it here.

**Comment by gurgeous** [comment]
pls! this is a large pain point. thanks for all your hard work Johnson.

**Comment by johnsoncodehk** [comment]
Don't know which version it is, but this has been fixed.
