### ISSUE TITLE
The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by bitmonti** [volarjs/volar.js#41]
**Bug**
```
Error: Debug Failure. False expression: y:/mapped_network_drive/path/to/project/node_modules/vue/dist/vue.d.ts linked to nonexistent file //server/linux/path/to/project/node_modules/vue/dist/vue.d.ts
```

**Project Info:**
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@9.6.6
- Builder:          vite
- User Config:      app, css, i18n, modules, runtimeConfig
- Runtime Modules:  nuxt-icon@0.4.0, @nuxt/image-edge@1.0.0-28059208.2abef1b, @nuxtjs/i18n@8.0.0-beta.12, @nuxtjs/tailwindcss@6.6.8, @vueuse/nuxt@10.1.2
- Build Modules:    -

**Additional Infomation**
```
[@volar-plugins/typescript] sourceFile not found file:///y%3A/path/to/project/app.vue.js
c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:39898
```

**Comment by bitmonti** [comment]
It seems to be an issue of builtin "TypeScript and JavaScript Language Features". But when I switch to takeover mode, im getting this error message.

Thanks for considering my request.

**Comment by johnsoncodehk** [comment]
Do you still get this error with Vue Language Features >= v1.8.3?
