### ISSUE TITLE
Custom SFC blocks

### ISSUE THREAD

**Issue by Hebilicious** [volarjs/volar.js#52]
Hello there ! Thanks for making Volar, it is really awesome.

I want to implement server blocks for Nuxt https://github.com/nuxt/nuxt/issues/20802
The SFC is going to look like [this](https://play.vuejs.org/#eNqNUstOwzAQ/BXLp1YqiVBvUVsJUBFwAATcWA5Wsk1dXDvyo40U5d9ZO7RUCFXkkmRnPDs7645fNU22C8gLPnNod2iZErqeA/cO+AI0to2xnlW4EkGlt9S43KH2d0JXCu1ohPFvzOYL1oFm9JRGO6MwU6b+BkGDt+iD1ey9k1XBLick5UorGy+NLhjwNSplLvbGqgp4/wG6p1OzfDBFRmYDmzmSaX6ZjA0961glvGA9m7Pg8BZ9uR4Bz0Ujc28qQ1RSPPUW6WOW5//3RH4SvuAT6k1aK1lnG2c05ZeGB16abSMpl6ekQk2LQyzABcntH1LN24CTQ71cY/n5R33j2lgD/mwxBQH8iHlha/QDvHx9xJa+j+DWVEER+wz4gpRDiB4H2nVI6zzhJbf327h/qes3t2w9ancYKhqNzD7xgdMlujkz+o/daTZN52jDvP8CBt3XqQ==).

Under the hood, this *entire* block content would be removed, and processed separately by Nuxt. It wouldn't be present in the component itself, it's essentially isolated from <scripts> blocks.

Adding lang="ts" make the color syntax work, but I want all the Typescript features to work, such as following the correct tsconfig and also typechecking.
I've considered using a `<script server>` tag too, but it seems to be easier with a custom name.
What needs to happen with Volar to make something like this work ? I would appreciate if you could point me in the right direction. 
Thanks !

**Comment by Hebilicious** [comment]
I've create a nuxt module that use custom blocks. 

https://github.com/Hebilicious/server-block-nuxt

**Comment by johnsoncodehk** [comment]
hey @Hebilicious, please note that `@volar/vue-langauge-core` is renamed to `@vue/language-core`.

https://github.com/Hebilicious/server-block-nuxt/blob/main/packages/sfc-server-volar/package.json#L41

**Comment by Hebilicious** [comment]
> hey @Hebilicious, please note that `@volar/vue-langauge-core` is renamed to `@vue/language-core`.
> 
> [Hebilicious/server-block-nuxt@`main`/packages/sfc-server-volar/package.json#L41](https://github.com/Hebilicious/server-block-nuxt/blob/main/packages/sfc-server-volar/package.json?rgh-link-date=2023-07-12T19%3A07%3A07Z#L41)

Thanks, I've updated. I haven't been able to understand why defaults exports can't be used in my custom blocks though.

**Comment by johnsoncodehk** [comment]
You should use `export = ` or `module.exports = ` instead of `export default`.
