### ISSUE TITLE
Wrong initial formatting with simultaneous <script> and <script setup>

### ISSUE THREAD

**Issue by silentmantra** [volarjs/volar.js#79]
I often use `<script>` together with `<script setup>` in SFC to cache some data across components.
Unfortunately it seems Volar wrongly formats this combination initially.
When I format manually, close and open the file, everything works fine afterwards, but that's annonying:

![volar-wrong-formatting](https://github.com/volarjs/volar.js/assets/1520737/f18598df-5356-4479-8179-2b099b957713)

Tried the pre-release version - the same problem:

```
Vue Language Features (Volar)
v1.8.23

Visual Studio Code
Version: 1.84.1
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:35:59.022Z (23 hrs ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.84.1 Chrome/114.0.5735.289 Electron/25.9.2 Safari/537.36
```

**Comment by johnsoncodehk** [comment]
Thanks for the report, and I think this problem no longer exists. If not, please open an issue in the vuejs/language-tools repo.
